version: "3.9"

services:
  training:
    image: mtgradient-training:latest
    tty: true
    volumes:
      - ./:/app/mtgradient/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    # environment:
    ports:
      - 8888:8888
    command: python -m notebook --allow-root --ip 0.0.0.0 --no-browser --NotebookApp.token=mtg

  mlflow-server:
    image: mtgradient-training:latest
    tty: true
    volumes:
      - ./:/app/mtgradient/
    ports:
      - 5000:5000
    command: mlflow ui --host 0.0.0.0
